In [1]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [2]:
x = np.arange(1, 51)
y = np.arange(10, 501, 10)

In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [4]:
y

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500])

In [12]:
def gradient_descent(x,y):
    weight=0.5 #here i change the value of weight 
    bias=0.1
    lr=0.05
    n=len(x)
    itr=50
    
    for i in range(itr):
        # forward propogation
        y_hat = x * weight + bias
        mse = mean_squared_error(y, y_hat)
        
        #backward propogation
        dw = -(2/n) * sum(x * (y-y_hat))
        db = -(2/n) * sum(y-y_hat)
        
        weight = weight - (lr * dw)
        bias = bias - (lr * db)
        print(f"Itr ={i}, W={weight}, B={bias}, MSE={mse}")

In [13]:
gradient_descent(x,y)

Itr =0, W=815.82, B=24.31499999999999, MSE=77431.185
Itr =1, W=-68425.83025, B=-2032.9575000000004, MSE=558463291.8529251
Itr =2, W=5811974.238337501, B=172681.7053875, MSE=4027852483802.1963
Itr =3, W=-493585493.97167516, B=-14665095.27291189, MSE=2.9050424385856536e+16
Itr =4, W=41918126014.942566, B=1245444449.3821514, MSE=2.0952285625955402e+20
Itr =5, W=-3559928874855.302, B=-105770321308.15959, MSE=1.5111595862446246e+24
Itr =6, W=302329679351666.6, B=8982625341729.174, MSE=1.0899065313762855e+28
Itr =7, W=-2.5675578987609464e+16, B=-762856319539168.2, MSE=7.860825937575001e+31
Itr =8, W=2.1805181607134892e+18, B=6.478615573081891e+16, MSE=5.669530610374726e+35
Itr =9, W=-1.8518217063365316e+20, B=-5.50201376966166e+18, MSE=4.0890839712311486e+39
Itr =10, W=1.572673731337811e+22, B=4.6726272272311996e+20, MSE=2.9492049470872105e+43
Itr =11, W=-1.3356051809830768e+24, B=-3.968264369866337e+22, MSE=2.127080265682321e+47
Itr =12, W=1.1342729034784563e+26, B=3.370078832178048e+24, MS

In [14]:
y_hat = x * 5.53 + 2.81

In [15]:
y_hat

array([  8.34,  13.87,  19.4 ,  24.93,  30.46,  35.99,  41.52,  47.05,
        52.58,  58.11,  63.64,  69.17,  74.7 ,  80.23,  85.76,  91.29,
        96.82, 102.35, 107.88, 113.41, 118.94, 124.47, 130.  , 135.53,
       141.06, 146.59, 152.12, 157.65, 163.18, 168.71, 174.24, 179.77,
       185.3 , 190.83, 196.36, 201.89, 207.42, 212.95, 218.48, 224.01,
       229.54, 235.07, 240.6 , 246.13, 251.66, 257.19, 262.72, 268.25,
       273.78, 279.31])