In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[10, 20], [30, 40]])
b = tf.constant([[50, 60], [70, 80]])

In [3]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [4]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 60],
       [70, 80]])>

In [6]:
# Perform matrix multiplication
c = tf.matmul(a, b)

In [8]:
print(c)

tf.Tensor(
[[1900 2200]
 [4300 5000]], shape=(2, 2), dtype=int32)
